// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	hostsList: () => typedError<Host[], string>(__TAURI_INVOKE("hosts_list")),
	hostsGet: (id: number) => typedError<{
	id: number,
	name: string,
	group_id: number | null,
	tags: string[],
	address: string,
	port: number,
	username: string | null,
	protocol: HostProtocol,
	credential_id: number | null,
	jump_chain_id: number | null,
	encoding_override: string | null,
	theme_override: string | null,
	monitor_enabled: boolean,
	is_production: boolean,
	notes: string | null,
	created_at: number,
	updated_at: number,
} | null, string>(__TAURI_INVOKE("hosts_get", { id })),
	hostsCreate: (input: HostInput) => typedError<Host, string>(__TAURI_INVOKE("hosts_create", { input })),
	hostsUpdate: (id: number, input: HostInput) => typedError<Host, string>(__TAURI_INVOKE("hosts_update", { id, input })),
	hostsDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("hosts_delete", { id })),
	hostsListByGroup: (groupId: number | null) => typedError<Host[], string>(__TAURI_INVOKE("hosts_list_by_group", { groupId })),
	hostsSearch: (query: string) => typedError<Host[], string>(__TAURI_INVOKE("hosts_search", { query })),
	knownHostsList: () => typedError<KnownHost[], string>(__TAURI_INVOKE("known_hosts_list")),
	knownHostsUpsert: (hostKey: string, fingerprint: string) => typedError<KnownHost, string>(__TAURI_INVOKE("known_hosts_upsert", { hostKey, fingerprint })),
	knownHostsVerify: (hostKey: string, fingerprint: string) => typedError<KnownHost, string>(__TAURI_INVOKE("known_hosts_verify", { hostKey, fingerprint })),
	knownHostsMarkChanged: (hostKey: string, fingerprint: string) => typedError<KnownHost, string>(__TAURI_INVOKE("known_hosts_mark_changed", { hostKey, fingerprint })),
	/**
	 *  删除 = 忘记该端点（B9 管理页，Task 6 Phase 3）：行消失后下次连接重走
	 *  TOFU（首见 pending）。返回是否有行被删（幂等面）。
	 */
	knownHostsDelete: (hostKey: string) => typedError<boolean, string>(__TAURI_INVOKE("known_hosts_delete", { hostKey })),
	credentialsList: () => typedError<Credential[], string>(__TAURI_INVOKE("credentials_list")),
	credentialsGet: (id: number) => typedError<{
	id: number,
	kind: CredentialKind,
	key_pub: string | null,
	created_at: number,
	updated_at: number,
} | null, string>(__TAURI_INVOKE("credentials_get", { id })),
	credentialsCreate: (input: CredentialInput) => typedError<Credential, string>(__TAURI_INVOKE("credentials_create", { input })),
	credentialsUpdate: (id: number, patch: CredentialPatch) => typedError<Credential, string>(__TAURI_INVOKE("credentials_update", { id, patch })),
	credentialsDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("credentials_delete", { id })),
	/**
	 *  明文单点出库（`field` 反序列化依赖 SecretField 的 serde snake_case 面，
	 *  Task 4 评审转交必办①）。
	 */
	credentialsReveal: (id: number, field: SecretField) => typedError<string | null, string>(__TAURI_INVOKE("credentials_reveal", { id, field })),
	snippetsList: () => typedError<Snippet[], string>(__TAURI_INVOKE("snippets_list")),
	snippetsGet: (id: number) => typedError<{
	id: number,
	name: string,
	body: string,
	variables: string[],
	tags: string[],
	host_scope: number | null,
	created_at: number,
	updated_at: number,
} | null, string>(__TAURI_INVOKE("snippets_get", { id })),
	snippetsSearch: (query: string) => typedError<Snippet[], string>(__TAURI_INVOKE("snippets_search", { query })),
	snippetsCreate: (input: SnippetInput) => typedError<Snippet, string>(__TAURI_INVOKE("snippets_create", { input })),
	snippetsUpdate: (id: number, input: SnippetInput) => typedError<Snippet, string>(__TAURI_INVOKE("snippets_update", { id, input })),
	snippetsDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("snippets_delete", { id })),
};

/* Types */
/**
 *  凭据。**不含任何密钥材料**（`*_enc` 列不进结构体）——明文只经
 *  [`Credentials::reveal`] 单点取回，序列化面（TS 类型同构）天然无密钥。
 */
export type Credential = {
	id: number,
	kind: CredentialKind,
	key_pub: string | null,
	created_at: number,
	updated_at: number,
};

/**
 *  新建凭据的输入：`secret`（password/key 的主体：口令或私钥）、`passphrase`、
 *  `totp_secret` 为明文，存储层 seal；`key_pub` 非敏感，明文存储。
 */
export type CredentialInput = {
	kind: CredentialKind,
	secret: string | null,
	key_pub: string | null,
	passphrase: string | null,
	totp_secret: string | null,
};

/**
 *  凭据类型（serde 小写，DB CHECK 同名约束——0001 建 CHECK，0010 放开
 *  ftp/ftps）。FTP/FTPS 凭据 = 密码型（secret 通道密封），与 SSH 密码凭据
 *  同存储面，只在 UI/连接分派时区分协议（Phase 2 Task 5）。
 */
export type CredentialKind = "password" | "key" | "totp" | "ftp" | "ftps";

/**  更新凭据的补丁：全部 `None = 保留现值`（UI 语义：未重输的密钥不重密封）。 */
export type CredentialPatch = {
	kind: CredentialKind | null,
	secret: string | null,
	key_pub: string | null,
	passphrase: string | null,
	totp_secret: string | null,
};

/**
 *  主机。tags 为 JSON 列；credential_id / group_id 可空、FK ON DELETE SET NULL；
 *  jump_chain_id 的目标表（jump_chains）未建，暂无 FK（0002 迁移注释）。
 *  username（0003 迁移）为登录用户名，可空（未指定时连接侧回退当前用户）。
 *  protocol（0010 迁移）为主机协议，缺省 ssh（FilePanel 后端切换依据）。
 *  is_production（0012 迁移）为生产环境标记——终端红框 + 页签 PROD 徽标 +
 *  danger 输入提醒的消费依据（B11 防呆），缺省 false。
 */
export type Host = {
	id: number,
	name: string,
	group_id: number | null,
	tags: string[],
	address: string,
	port: number,
	username: string | null,
	protocol: HostProtocol,
	credential_id: number | null,
	jump_chain_id: number | null,
	encoding_override: string | null,
	theme_override: string | null,
	monitor_enabled: boolean,
	is_production: boolean,
	notes: string | null,
	created_at: number,
	updated_at: number,
};

/**  新建/全量更新主机的输入（字段名与 [`Host`] 可编辑子集同构）。 */
export type HostInput = {
	name: string,
	group_id: number | null,
	tags: string[],
	address: string,
	port: number,
	username: string | null,
	/**  serde default：旧调用面（测试/驱动脚本）不传 = ssh（0010 语义兼容）。 */
	protocol?: HostProtocol,
	credential_id: number | null,
	jump_chain_id: number | null,
	encoding_override: string | null,
	theme_override: string | null,
	monitor_enabled: boolean,
	/**  serde default：旧载荷不传 = 非生产（0012 语义兼容——标记是显式动作）。 */
	is_production?: boolean,
	notes: string | null,
};

/**
 *  主机协议（0010 迁移，Phase 2 Task 5）：ssh | ftp | ftps。`None`/缺省 =
 *  ssh（存量行零迁移）；FTP/FTPS 主机为文件传输会话（无 PTY 终端）。
 */
export type HostProtocol = "ssh" | "ftp" | "ftps";

/**  已知主机指纹（TOFU 记录，以 host 端点为主键、fingerprint = 当前信任锚）。 */
export type KnownHost = {
	/**
	 *  host 端点键（[`host_endpoint_key`]；0004 前的存量行为
	 *  `"legacy:{fingerprint}"` 虚拟端点，信任关系待下次连接重建）。
	 */
	host_key: string,
	/**
	 *  当前信任锚：最近一次 verify 接受的指纹。mark_changed **不覆盖**本列
	 *  （拒绝疑似 MITM 后仍钉着原钥匙，OpenSSH「警告且不写 known_hosts」语义）。
	 */
	fingerprint: string,
	first_seen: number,
	verified: boolean,
	/**
	 *  最近一次检测到该端点指纹与信任锚**不一致**的时间（事件时间戳而非状态
	 *  属性）——之后 re-verify 回 ok 也**保留不清空**（「何时出过事」的历史不随
	 *  信任恢复而抹除）。重复检测到不一致会刷新（= 最近一次检测到）。
	 *  从未变更过则为 None。
	 */
	changed_at: number | null,
	state: KnownHostState,
};

/**
 *  主机指纹状态机（0004 起按 host 端点记账）：
 *  `pending`（首见未核验）→ `ok`（用户 verify）→ `changed`（key 变更，verified
 *  作废）——verify 可再回到 ok。
 */
export type KnownHostState = "ok" | "changed" | "pending";

/**
 *  可开封的密文字段（列名与 AAD 字段名一一对应）。
 *  serde 面（snake_case："secret"/"passphrase"/"totp_secret"）与 TS `SecretField`
 *  联合类型逐字同构——Task 4 评审转交必办①：`credentials_reveal` 命令的 `field`
 *  参数反序列化依赖这里（TS 侧 totp_secret 传 "totp_secret"，缺 derive 会地雷式失败）。
 */
export type SecretField = "secret" | "passphrase" | "totp_secret";

/**
 *  命令片段：body 支持 `{{var}}` 模板，variables 为变量名清单（JSON 列）。
 *  host_scope 可选绑定单机；删该主机 → 转全局（SET NULL）。
 */
export type Snippet = {
	id: number,
	name: string,
	body: string,
	variables: string[],
	tags: string[],
	host_scope: number | null,
	created_at: number,
	updated_at: number,
};

/**  新建/全量更新 snippet 的输入。 */
export type SnippetInput = {
	name: string,
	body: string,
	variables: string[],
	tags: string[],
	host_scope: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

