// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	hostsList: () => typedError<Host[], string>(__TAURI_INVOKE("hosts_list")),
	hostsGet: (id: number) => typedError<{
	id: number,
	name: string,
	group_id: number | null,
	tags: string[],
	address: string,
	port: number,
	username: string | null,
	protocol: HostProtocol,
	credential_id: number | null,
	jump_chain_id: number | null,
	encoding_override: string | null,
	theme_override: string | null,
	monitor_enabled: boolean,
	is_production: boolean,
	notes: string | null,
	created_at: number,
	updated_at: number,
} | null, string>(__TAURI_INVOKE("hosts_get", { id })),
	hostsCreate: (input: HostInput) => typedError<Host, string>(__TAURI_INVOKE("hosts_create", { input })),
	hostsUpdate: (id: number, input: HostInput) => typedError<Host, string>(__TAURI_INVOKE("hosts_update", { id, input })),
	hostsDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("hosts_delete", { id })),
	hostsListByGroup: (groupId: number | null) => typedError<Host[], string>(__TAURI_INVOKE("hosts_list_by_group", { groupId })),
	hostsSearch: (query: string) => typedError<Host[], string>(__TAURI_INVOKE("hosts_search", { query })),
	knownHostsList: () => typedError<KnownHost[], string>(__TAURI_INVOKE("known_hosts_list")),
	knownHostsUpsert: (hostKey: string, fingerprint: string) => typedError<KnownHost, string>(__TAURI_INVOKE("known_hosts_upsert", { hostKey, fingerprint })),
	knownHostsVerify: (hostKey: string, fingerprint: string) => typedError<KnownHost, string>(__TAURI_INVOKE("known_hosts_verify", { hostKey, fingerprint })),
	knownHostsMarkChanged: (hostKey: string, fingerprint: string) => typedError<KnownHost, string>(__TAURI_INVOKE("known_hosts_mark_changed", { hostKey, fingerprint })),
	/**
	 *  删除 = 忘记该端点（B9 管理页，Task 6 Phase 3）：行消失后下次连接重走
	 *  TOFU（首见 pending）。返回是否有行被删（幂等面）。
	 */
	knownHostsDelete: (hostKey: string) => typedError<boolean, string>(__TAURI_INVOKE("known_hosts_delete", { hostKey })),
	credentialsList: () => typedError<Credential[], string>(__TAURI_INVOKE("credentials_list")),
	credentialsGet: (id: number) => typedError<{
	id: number,
	kind: CredentialKind,
	key_pub: string | null,
	created_at: number,
	updated_at: number,
} | null, string>(__TAURI_INVOKE("credentials_get", { id })),
	credentialsCreate: (input: CredentialInput) => typedError<Credential, string>(__TAURI_INVOKE("credentials_create", { input })),
	credentialsUpdate: (id: number, patch: CredentialPatch) => typedError<Credential, string>(__TAURI_INVOKE("credentials_update", { id, patch })),
	credentialsDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("credentials_delete", { id })),
	/**
	 *  明文单点出库（`field` 反序列化依赖 SecretField 的 serde snake_case 面，
	 *  Task 4 评审转交必办①）。
	 */
	credentialsReveal: (id: number, field: SecretField) => typedError<string | null, string>(__TAURI_INVOKE("credentials_reveal", { id, field })),
	snippetsList: () => typedError<Snippet[], string>(__TAURI_INVOKE("snippets_list")),
	snippetsGet: (id: number) => typedError<{
	id: number,
	name: string,
	body: string,
	variables: string[],
	tags: string[],
	host_scope: number | null,
	created_at: number,
	updated_at: number,
} | null, string>(__TAURI_INVOKE("snippets_get", { id })),
	snippetsSearch: (query: string) => typedError<Snippet[], string>(__TAURI_INVOKE("snippets_search", { query })),
	snippetsCreate: (input: SnippetInput) => typedError<Snippet, string>(__TAURI_INVOKE("snippets_create", { input })),
	snippetsUpdate: (id: number, input: SnippetInput) => typedError<Snippet, string>(__TAURI_INVOKE("snippets_update", { id, input })),
	snippetsDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("snippets_delete", { id })),
	/**  写入/覆盖一个密文项（upsert）。 */
	secretSet: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("secret_set", { key, value })),
	/**  读一个密文项（明文单点出库；未设置 → None）。 */
	secretGet: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("secret_get", { key })),
	/**  删除一个密文项（未知 key 显式报错——provider 已删而密文在即 bug，宁可响）。 */
	secretDelete: (key: string) => typedError<null, string>(__TAURI_INVOKE("secret_delete", { key })),
	/**  密文项存在性（不派生明文——设置页「已保存 key」标记）。 */
	secretContains: (key: string) => typedError<boolean, string>(__TAURI_INVOKE("secret_contains", { key })),
	historyInsert: (input: HistoryInput) => typedError<HistoryEntry, string>(__TAURI_INVOKE("history_insert", { input })),
	/**
	 *  `query` 空白 = 最近记录（面板初始态）；`host_id` 缺省 = 跨主机；
	 *  `limit` 缺省 [`HISTORY_SEARCH_LIMIT`]。≥3 字符 FTS trigram / 超短 LIKE 兜底
	 *  （Rust 层分派，与 hosts_search 同语义）。
	 */
	historySearch: (query: string, hostId: number | null, limit: number | null) => typedError<HistoryEntry[], string>(__TAURI_INVOKE("history_search", { query, hostId, limit })),
	/**
	 *  会话维度的命令序列（Phase 2 Task 7 纪要数据源）：id 升序（≈ts 时序），
	 *  `limit` 缺省 [`HISTORY_SESSION_LIMIT`]。明文面（锁定可读，同 history_search）。
	 */
	historyListSession: (hostId: number, sessionId: string, limit: number | null) => typedError<HistoryEntry[], string>(__TAURI_INVOKE("history_list_session", { hostId, sessionId, limit })),
	summaryInsert: (input: SummaryInput) => typedError<SummaryEntry, string>(__TAURI_INVOKE("summary_insert", { input })),
	/**  `host_id` 缺省 = 跨主机；`limit` 缺省 [`SUMMARIES_LIST_LIMIT`]。 */
	summaryList: (hostId: number | null, limit: number | null) => typedError<SummaryEntry[], string>(__TAURI_INVOKE("summary_list", { hostId, limit })),
	hostGroupsList: () => typedError<HostGroup[], string>(__TAURI_INVOKE("host_groups_list")),
	hostGroupsCreate: (name: string, parentId: number | null, color: string | null) => typedError<HostGroup, string>(__TAURI_INVOKE("host_groups_create", { name, parentId, color })),
	hostGroupsUpdate: (id: number, name: string, parentId: number | null, color: string | null) => typedError<HostGroup, string>(__TAURI_INVOKE("host_groups_update", { id, name, parentId, color })),
	hostGroupsDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("host_groups_delete", { id })),
	/**
	 *  导入 ~/.ssh/config（`path` 缺省时用 `~/.ssh/config`；前端 MVP 无文件选择器，
	 *  传 None 即默认路径——留参数位给后续文件选择对话框）。
	 *  解析与去重规则见 ssh_config 模块文档；报告（新增/跳过/错误行）由前端对话框展示。
	 */
	importSshConfig: (path: string | null) => typedError<ImportReport, string>(__TAURI_INVOKE("import_ssh_config", { path })),
	/**
	 *  导入 Xshell 会话（Phase 2 Task 10，B3）。`path` = 会话目录或单个 .xsh；
	 *  缺省回落 Windows 惯例会话目录（不存在即报错——mac/Linux 无默认位置）。
	 *  解析规则与去重见 importers::xshell 模块文档；报告同构 ssh-config 导入。
	 */
	importXshellSessions: (path: string | null) => typedError<ImportReport, string>(__TAURI_INVOKE("import_xshell_sessions", { path })),
	/**
	 *  导入 Tabby 配置（Phase 2 Task 10，B3）。`path` 必传（配置 JSON 无跨平台
	 *  惯例位置——前端经文件对话框选定）。解析规则见 importers::tabby 模块文档。
	 */
	importTabbyConfig: (path: string) => typedError<ImportReport, string>(__TAURI_INVOKE("import_tabby_config", { path })),
	/**
	 *  CSV 导出主机清单。`path` 缺省写到系统下载目录 `ottr-hosts.csv`；返回落盘路径。
	 *  CSV 组装（RFC4180 转义 + 实体 join）在 ottr-vault `hosts_csv`（BL-206：随
	 *  实体同库可独立单测）；本命令只保留路径解析与落盘。
	 */
	exportHostsCsv: (path: string | null) => typedError<string, string>(__TAURI_INVOKE("export_hosts_csv", { path })),
};

/* Types */
/**
 *  凭据。**不含任何密钥材料**（`*_enc` 列不进结构体）——明文只经
 *  [`Credentials::reveal`] 单点取回，序列化面（TS 类型同构）天然无密钥。
 */
export type Credential = {
	id: number,
	kind: CredentialKind,
	key_pub: string | null,
	created_at: number,
	updated_at: number,
};

/**
 *  新建凭据的输入：`secret`（password/key 的主体：口令或私钥）、`passphrase`、
 *  `totp_secret` 为明文，存储层 seal；`key_pub` 非敏感，明文存储。
 */
export type CredentialInput = {
	kind: CredentialKind,
	secret: string | null,
	key_pub: string | null,
	passphrase: string | null,
	totp_secret: string | null,
};

/**
 *  凭据类型（serde 小写，DB CHECK 同名约束——0001 建 CHECK，0010 放开
 *  ftp/ftps）。FTP/FTPS 凭据 = 密码型（secret 通道密封），与 SSH 密码凭据
 *  同存储面，只在 UI/连接分派时区分协议（Phase 2 Task 5）。
 */
export type CredentialKind = "password" | "key" | "totp" | "ftp" | "ftps";

/**  更新凭据的补丁：全部 `None = 保留现值`（UI 语义：未重输的密钥不重密封）。 */
export type CredentialPatch = {
	kind: CredentialKind | null,
	secret: string | null,
	key_pub: string | null,
	passphrase: string | null,
	totp_secret: string | null,
};

/**  历史行（serde 面与 `frontend/vault/api.ts` 的 `HistoryEntry` 同构，snake_case）。 */
export type HistoryEntry = {
	id: number,
	host_id: number,
	command: string,
	cwd: string | null,
	exit_code: number | null,
	session_id: string | null,
	/**  秒级 Unix 时间（实体表同口径）。 */
	ts: number,
};

/**  新建历史行的输入（ts 由存储层定；command 非空校验在存储层）。 */
export type HistoryInput = {
	host_id: number,
	command: string,
	cwd: string | null,
	exit_code: number | null,
	session_id: string | null,
};

/**
 *  主机。tags 为 JSON 列；credential_id / group_id 可空、FK ON DELETE SET NULL；
 *  jump_chain_id 的目标表（jump_chains）未建，暂无 FK（0002 迁移注释）。
 *  username（0003 迁移）为登录用户名，可空（未指定时连接侧回退当前用户）。
 *  protocol（0010 迁移）为主机协议，缺省 ssh（FilePanel 后端切换依据）。
 *  is_production（0012 迁移）为生产环境标记——终端红框 + 页签 PROD 徽标 +
 *  danger 输入提醒的消费依据（B11 防呆），缺省 false。
 */
export type Host = {
	id: number,
	name: string,
	group_id: number | null,
	tags: string[],
	address: string,
	port: number,
	username: string | null,
	protocol: HostProtocol,
	credential_id: number | null,
	jump_chain_id: number | null,
	encoding_override: string | null,
	theme_override: string | null,
	monitor_enabled: boolean,
	is_production: boolean,
	notes: string | null,
	created_at: number,
	updated_at: number,
};

/**  主机分组（树形：parent_id 自引用）。删父组 → 子组提根；删组 → 组内主机脱离分组。 */
export type HostGroup = {
	id: number,
	name: string,
	parent_id: number | null,
	color: string | null,
	created_at: number,
	updated_at: number,
};

/**  新建/全量更新主机的输入（字段名与 [`Host`] 可编辑子集同构）。 */
export type HostInput = {
	name: string,
	group_id: number | null,
	tags: string[],
	address: string,
	port: number,
	username: string | null,
	/**  serde default：旧调用面（测试/驱动脚本）不传 = ssh（0010 语义兼容）。 */
	protocol?: HostProtocol,
	credential_id: number | null,
	jump_chain_id: number | null,
	encoding_override: string | null,
	theme_override: string | null,
	monitor_enabled: boolean,
	/**  serde default：旧载荷不传 = 非生产（0012 语义兼容——标记是显式动作）。 */
	is_production?: boolean,
	notes: string | null,
};

/**
 *  主机协议（0010 迁移，Phase 2 Task 5）：ssh | ftp | ftps。`None`/缺省 =
 *  ssh（存量行零迁移）；FTP/FTPS 主机为文件传输会话（无 PTY 终端）。
 */
export type HostProtocol = "ssh" | "ftp" | "ftps";

/**  导入报告（裁定 #4：新增 N、跳过 N、解析错误行列表，导入完成对话框展示）。 */
export type ImportReport = {
	added: number,
	skipped_wildcards: number,
	skipped_duplicates: number,
	errors: string[],
};

/**  已知主机指纹（TOFU 记录，以 host 端点为主键、fingerprint = 当前信任锚）。 */
export type KnownHost = {
	/**
	 *  host 端点键（[`host_endpoint_key`]；0004 前的存量行为
	 *  `"legacy:{fingerprint}"` 虚拟端点，信任关系待下次连接重建）。
	 */
	host_key: string,
	/**
	 *  当前信任锚：最近一次 verify 接受的指纹。mark_changed **不覆盖**本列
	 *  （拒绝疑似 MITM 后仍钉着原钥匙，OpenSSH「警告且不写 known_hosts」语义）。
	 */
	fingerprint: string,
	first_seen: number,
	verified: boolean,
	/**
	 *  最近一次检测到该端点指纹与信任锚**不一致**的时间（事件时间戳而非状态
	 *  属性）——之后 re-verify 回 ok 也**保留不清空**（「何时出过事」的历史不随
	 *  信任恢复而抹除）。重复检测到不一致会刷新（= 最近一次检测到）。
	 *  从未变更过则为 None。
	 */
	changed_at: number | null,
	state: KnownHostState,
};

/**
 *  主机指纹状态机（0004 起按 host 端点记账）：
 *  `pending`（首见未核验）→ `ok`（用户 verify）→ `changed`（key 变更，verified
 *  作废）——verify 可再回到 ok。
 */
export type KnownHostState = "ok" | "changed" | "pending";

/**
 *  可开封的密文字段（列名与 AAD 字段名一一对应）。
 *  serde 面（snake_case："secret"/"passphrase"/"totp_secret"）与 TS `SecretField`
 *  联合类型逐字同构——Task 4 评审转交必办①：`credentials_reveal` 命令的 `field`
 *  参数反序列化依赖这里（TS 侧 totp_secret 传 "totp_secret"，缺 derive 会地雷式失败）。
 */
export type SecretField = "secret" | "passphrase" | "totp_secret";

/**
 *  命令片段：body 支持 `{{var}}` 模板，variables 为变量名清单（JSON 列）。
 *  host_scope 可选绑定单机；删该主机 → 转全局（SET NULL）。
 */
export type Snippet = {
	id: number,
	name: string,
	body: string,
	variables: string[],
	tags: string[],
	host_scope: number | null,
	created_at: number,
	updated_at: number,
};

/**  新建/全量更新 snippet 的输入。 */
export type SnippetInput = {
	name: string,
	body: string,
	variables: string[],
	tags: string[],
	host_scope: number | null,
};

/**
 *  纪要行（serde 面与 `frontend/vault/api.ts` 的 `SummaryEntry` 同构，snake_case；
 *  `summary` 为开封后的明文——密文只在 `summary_enc` 列，出库即开）。
 */
export type SummaryEntry = {
	id: number,
	host_id: number,
	session_id: string,
	summary: string,
	/**  摘要覆盖的命令条数（面板徽标 + 溯源面）。 */
	command_count: number,
	/**  秒级 Unix 时间（upsert 时 = 最新一次生成时刻）。 */
	ts: number,
};

/**  新建/覆盖纪要的输入（ts/id 由存储层定）。 */
export type SummaryInput = {
	host_id: number,
	session_id: string,
	summary: string,
	command_count: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

